### ISSUE TITLE
recover from lost ledger

### ISSUE THREAD

**Issue by 3cl1ps** [hirishh/liskish-wallet#25]
Hey, i was using a ledger i lost to secure my funds. I still have the seed.
When i log in liskish using that seed, i end up on a wrong address.

I tried this tool https://iancoleman.io/bip39/ with m/44'/134'/0'/0'/0' as derivation path but still no success : addresses are starting with a 1 and lisk is not there in coin list.

Is there any way to recover my funds ?

**Comment by hirishh** [comment]
Hello @3cl1ps,

Yes there is multiple ways, but the only 1 without involving coding: use another ledger with the same seed.
Instead, if a little bit of NodeJS code doesn't afraid you, this tool is exactly what you need: https://github.com/lisk-builders/lisk-hd-key

Another way could be to clone bip39 repo and implement the lisk address derivation starting from the publickey of path m/44'/134'/0' (In lisk we use only 3 path).

Liskish Wallet cannot help because Ledger derivation from a seed is completely different from Lisk Native seed.

If something is not clear do not hesitate to comment further!

**Comment by 3cl1ps** [comment]
Hey, thanks for fast answer.
I think i have a private key, just add ::
console.log(key.toString('hex'));
in getPublicKey method of index.js

I would like now to import it, something like bitcoin-cli importprivkey.
But i can't find anything like that neither in lisk-commander nor in lisk-core.
Do you know what program could i use ? i don't mind downloading the whole blockchain.

**Comment by hirishh** [comment]
There is no such a thing in Lisk Hub or Liskish Wallet. The quickest solution is to create a new account starting from a Lisk Native Seed and use NodeJs+privkey to sing and broadcast a transaction towards your newly created lisk account. Then you can sand it back when you are going to have a Ledger Nano again.
