### ISSUE TITLE
Trezor/Ledger: Status 409 : Transaction was rejected with errors

### ISSUE THREAD

**Issue by oreineke** [hirishh/liskish-wallet#29]
### Expected behaviour

Sending Lisk using a Trezor Model One or Ledger Nano X with PIN and Passphrase should work.

### Actual behaviour

After confirming the transaction on Trezor or Ledger, the following error message appears:

Status 409 : Transaction was rejected with errors

### Steps to reproduce

1. Use Liskish-Wallet 2.2.1-beta
2. Attach Trezor One or Ledger Nano X (with latest firmware), enter PIN (and separate passphrase, if on Trezor)
3. Send 1 Lisk to your own address (to init account)
4. Confirm on Trezor or on Ledger
5. You will receive an error "Status 409 : Transaction was rejected with errors" in Liskish-Wallet 2.2.1-beta

**Comment by hirishh** [comment]
Hello @oreineke,

The fact that the error is the same with Ledger and Trezor is kind a proof that the problem is not on hardware wallet software.

Before we go further, please:
1) Make sure that your pc local time is accurate (better if synchronized automatically with an internet service). Restart and try again.
2) If (1) is not working, try a different node.  When you connect on mainnet you see the node you are connected on the top of the page: for example `https://node06.lisk.io:443`. Go on the login page, select "Custom Node" and try a different one (change 06 with 04 or 05 for example).

Let me know.

**Comment by oreineke** [comment]
Thanks @hirishh,

I just tried again and this time it worked! Must have been some kind of a hick-up...
