### ISSUE TITLE
Mac version is not working (for me)

### ISSUE THREAD

**Issue by clementbappel** [hirishh/liskish-wallet#32]
Hi, 

I download the Mac version and when I open the app, it says that the developer cannot be verified. 

:(

**Comment by hirishh** [comment]
Hello @clementbappel,

This error doesn't mean it's not working. The problem is that I do not have an apple developer key in order to sign the app and your OS is warning you that the app is unsigned since it is not an official application but a third party one.

You can unlock it and make the os to install the app by following this guide: https://it.nmu.edu/docs/allowing-third-party-applications-install-macbook

Best, 

hirish

**Comment by hirishh** [comment]
Other solution is to install the lisk official wallet (it supports hardware wallet too), that his signed and you won't have any issue installing it: https://github.com/LiskHQ/lisk-desktop/releases
